name: gestion

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create directory
      run: mkdir new_folder
    - name: Display directory contents
      run: ls -l new_folder
    - name: Zip files
      run: |
        zip -r new_folder.zip new_folder
