name: zipper fichier

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Zipper le dossier
      run: |
        cd ${{ tuto-git }}
        zip -r _site.zip _site
    
